### ISSUE TITLE
Clear Sky - light flicker when moving

### ISSUE THREAD

**Issue by argosurvivors** [OpenXRay/xray-16#1877]
**Describe the bug**
Light starts flickering once you move, it is happening indoor and outdoor. The weather conditions must be rainy
for the error to show up. Rain drops are making light flicker when you are outside. When you are inside object and  it is raining, the walls will appear wet with vertical water lines which will also cause this flickering.

**To Reproduce**
1. Set up video to DX10 and High
2. Wait for the rain to start
3. move mouse left and right or walk front and back. Do this inside and outside of building while its raining
4. Lights will start flickering

**Expected behavior**
Flickering should happen only when its thunder and rain, this one is bind to camera movement and rain drops reflection.

**Screenshots, videos**
https://drive.google.com/file/d/1_PFXi24sANsNTICFzUVnt63gubavOIId/view?usp=drive_link

**BugTrap error report**
no crash or errors about it

**Desktop (please complete the following information):**
OpenXRay Release build 9605, May 26 2025 (Windows 64-bit, shared)
Nvidia graphics card GTX 1060, render DX10 

**Additional context**
I suspect this could be connected with some water shader disconecting and loading or having a way too strong reflection.

**Comment by Xottab-DUTY** [comment]
@argosurvivors, was this fixed with the recent lighting and rain fixes?

**Comment by argosurvivors** [comment]
The issue is still present when flashlight is directed at wet wall during rain and moving mouse left-right.
https://drive.google.com/file/d/1--L9VOaFJIfvtAvtShXDVYNrpJS4ve6I/view?usp=sharing
