### ISSUE TITLE
Some languages don't display properly - Call of Pripyat

### ISSUE THREAD

**Issue by gibroule** [OpenXRay/xray-16#865]
**Describe the bug**
When using french, german, spanish or italian, some texts don't display properly and white rectangles appear instead. But when I select one of these language and put the xrussian.db file in the localization folder, the text displays correctly with some special characters (such as accents) replaced by russian characters.

**Screenshots**
Title screen and intro work fine
![Screenshot_20210802_193231](https://user-images.githubusercontent.com/60317940/127904670-5ffb13ac-0f22-4cff-811a-44e163369bd2.png)

![Screenshot_20210802_193638](https://user-images.githubusercontent.com/60317940/127904838-963c409f-f410-49b8-b572-e1c94b614300.png)

But the rest is broken
![Screenshot_20210802_185753](https://user-images.githubusercontent.com/60317940/127904727-f07e0616-5cf5-4f10-b103-6e0ed60feba6.png)

![Screenshot_20210802_193354](https://user-images.githubusercontent.com/60317940/127904767-dd0180fb-ffa8-4c53-9ba2-1f03b073667e.png)

![Screenshot_20210802_185911](https://user-images.githubusercontent.com/60317940/127904747-405a686a-f34e-418c-8d1a-e2d964be902b.png)

Using xrussian.db the text comes back but with replaced characters
![Screenshot_20210802_194025](https://user-images.githubusercontent.com/60317940/127905180-c38bc10f-ae5d-4199-b277-70d96b136224.png)

**Desktop (please complete the following information):**
 - OS: Manjaro 5.13.5-1
 - OpenXRay build version commit [025328363f1c6b4473b26089b3755840dfcc8678] (01-08-2021)
 - I followed the instructions on git to compile and build a package of the game
 - I use the GOG version for the assets

**Comment by Xottab-DUTY** [comment]
Can you rename `Localization` folder to `localization` to see if it helps?

**Comment by gibroule** [comment]
Hi, I checked and all the games folders are in lowercase, it doesn't seem to be the issue

**Comment by Xottab-DUTY** [comment]
Lol, it seems that the issue has affected GitHub too :D
![image](https://user-images.githubusercontent.com/2989212/128078858-588a2974-2b4b-4b03-8ef0-6461a203f37b.png)

**Comment by gibroule** [comment]
Lol ! So I got more info on this from discord and after some tests, I can say that it is related to the resolution of the game. Anything over 1440x900 triggers the bug

**Comment by Xottab-DUTY** [comment]
@gibroule, can you check if the problem is fixed in the latest builds?

I suspect that this problem may be caused by the Linux filesystem case sensitivity and possibility that game files could have been made with Windows case **in**sensitivity in mind. Since there were changes made in the engine filesystem to address case sensitivity issues, this issue might have been also fixed.

**Comment by Xottab-DUTY** [comment]
> Since there were changes made in the engine filesystem to address case sensitivity issues, this issue might have been also fixed.

Oh... That changes to the filesystem were made before this issue was created...  (in PR #821)

@gibroule, maybe, can you still try the game with the latest builds, and then also try to revert commit 68d5eb821a043556061e428aee18deb1148cf3c0 to see, if it affects something or nothing at all?

**Comment by OPNA2608** [comment]
Still happens with the latest commit (2ee61edb12e644be5da78fb7ab6bef91f1d372d6) and with https://github.com/OpenXRay/xray-16/commit/68d5eb821a043556061e428aee18deb1148cf3c0 reverted.

**Comment by gibroule** [comment]
I still have the bug too

**Comment by AlexanderWKoenig** [comment]
Same issue is also present for me on Arch Linux tying to use the german localization.
When using the xenglish.db file und changing the language to german in user.ltx, the text is displayed but with cyrillic chars mixed in. 

I'm running a build from chaotic-aur which uses commit 1dc1c10508f6f7c9364149589cad8997d3aed6c2
I've also tried the latest commit [35fbe97] via an AUR. Here the issue is also present and it crashes when loading into game.

Would be nice to see this fixed.

**Comment by Xottab-DUTY** [comment]
@gibroule, @OPNA2608, @AlexanderWKoenig, can you guys check with the latest commits?

**Comment by OPNA2608** [comment]
On 78dd002c8c29c5eede7ff18eb5949e6c08576759, still happening.

![Bildschirmfoto_2022-05-07_10-56-39](https://user-images.githubusercontent.com/23431373/167247212-7b964da2-a8f9-43f3-954d-40bc895b9e81.png)

**Comment by gibroule** [comment]
I just tested 78dd002c8c29c5eede7ff18eb5949e6c08576759 and it's still happening too

**Comment by hartontw** [comment]
Same happening to me.

**CPU**: Intel i5-7500 (4) @ 3.800GHz
**GPU**: NVIDIA GeForce GTX 1060 6GB
**MEM**: 16GB DDR4

**OS**: Arch Linux x86_64
**Kernel**: 6.6.8-arch1-1
**Resolution**: 1920x1080, 1440x900
**WM**: awesome

**Game**: Stalker COP (Steam version)
**Install method**: [openxray](https://aur.archlinux.org/packages/openxray) (AUR)
**Language**: Spanish

<details> 
<summary>LOG</summary>

```
! Couldn't create surface from image: Parameter 'src' is invalid
OpenXRay Release Master Gold build 9113, Jan 19 2024 (Linux 64-bit, shared)
Custom build from commit[481d4dc8edd58866a79e072dc65355259c08fe5b] branch[makepkg]

command line

* CPU features: RDTSC, MMX, SSE, AVX
* CPU threads: 4

Initializing File System...
$fs_root$ = /home/harton/.local/share/GSC Game World/S.T.A.L.K.E.R. - Call of Pripyat/
using fs-ltx fsgame.ltx
FS: 43649 files cached 29 archives, 28Kb memory used.
Init FileSystem 0.245324 sec
-----loading \home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
-----loading \home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
! Failed to determine on which monitor the game is launched.
! SDL: Invalid window
Starting INPUT device...
Loading module: xrRender_GL
Available render modes[1]:
renderer_rgl
Executing config-script "user.ltx"...
[\home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] successfully loaded.
Selected renderer: renderer_rgl
Loading module: xrGame
Initializing Engine...
SOUND: OpenAL: system default sound device name is OpenAL Soft
Executing config-script "\home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx"...
[\home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx] successfully loaded.
Executing config-script "user.ltx"...
Executing config-script "\home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\rspec_extreme.ltx"...
[\home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\rspec_extreme.ltx] successfully loaded.
Executing config-script "\home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx"...
[\home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx] successfully loaded.
~ Invalid syntax in call to 'g_language'
~ Valid arguments: rus/spa
~ Invalid syntax in call to 'sv_adm_menu_ban_time'
~ Valid arguments: ui_mp_am_10_minutes/ui_mp_am_30_minutes/ui_mp_am_1_hour/ui_mp_am_6_hours/ui_mp_am_1_day/ui_mp_am_1_week/ui_mp_am_1_month/ui_mp_am_3_monthes/ui_mp_am_forever
~ Invalid syntax in call to 'sv_suspicious_actions_ban_time'
~ Valid arguments: ui_mp_am_10_minutes/ui_mp_am_30_minutes/ui_mp_am_1_hour/ui_mp_am_6_hours/ui_mp_am_1_day/ui_mp_am_1_week/ui_mp_am_1_month/ui_mp_am_3_monthes/ui_mp_am_forever
[\home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] successfully loaded.
SOUND: Selected device is OpenAL Soft
* SOUND: EFX extension: present
* sound : cache: 65537 kb, 4856 lines, 13820 bpl
Starting RENDER device...
* GPU vendor: [NVIDIA Corporation] device: [NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2]
* GPU OpenGL version: 4.1.0 NVIDIA 545.29.06
* GPU OpenGL shading language version: 4.10 NVIDIA via Cg compiler
* GPU OpenGL VTF units: [32] CTI units: [192]
* DVB created: 4096K
* DIB created: 512K
! Renderer doesn't support blender 'effects\shadow_world'
* HWDST/PCF supported and used
Starting engine...
* [ Linux ]: free[1961484 K], reserved[275544 K], committed[15694416 K]
* [ Render ]: textures[4213 K]
* [ x-ray  ]: process heap[255 K]
* [ x-ray  ]: economy: strings[7917 K], smem[0 K]
Config-file [\home\harton\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] saved successfully
Destroying Render...
----total count =  0
```

</details>

**Comment by Xottab-DUTY** [comment]
Hurray! Finally, this is fixed.

**Comment by laenion** [comment]
For me (German version, Linux) nothing seems to have changed - I still get the same broken text from the original bug report when using a "high" resolution (though it's working fine with a resolution of 1024x768 for example).

Could anybody previously affected confirm that this doesn't happen in the current version for them any more?

**Comment by OPNA2608** [comment]
On 6f5590d4751f2f7d761be4e346f87e97e1563cd6, still happening.

![Bildschirmfoto_2024-07-07_14-35-08](https://github.com/OpenXRay/xray-16/assets/23431373/7828a692-4ef9-49d8-b9e6-27da12441c4f)

**Comment by ikir83** [comment]
> On [6f5590d](https://github.com/OpenXRay/xray-16/commit/6f5590d4751f2f7d761be4e346f87e97e1563cd6), still happening.
> 
> ![Bildschirmfoto_2024-07-07_14-35-08](https://github.com/OpenXRay/xray-16/assets/23431373/7828a692-4ef9-49d8-b9e6-27da12441c4f)

Yes I confirm, trying the macOS port from MacSourcePorts.com and it happens on my setup as well with Italian localization.
